// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductManagement.DbContexts;

#nullable disable

namespace ProductManagement.Migrations
{
    [DbContext(typeof(ProductManagementContext))]
    [Migration("20240306115257_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductManagement.Entity.Product", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("FileId")
                        .HasColumnType("bigint");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Price")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            FileId = 1L,
                            IsDeleted = false,
                            Name = "Soğan Kuru Dökme Kg",
                            Price = 9.9000000000000004
                        },
                        new
                        {
                            Id = 2L,
                            FileId = 2L,
                            IsDeleted = false,
                            Name = "Hatay Arsuz Limonu Kg",
                            Price = 17.949999999999999
                        },
                        new
                        {
                            Id = 3L,
                            FileId = 3L,
                            IsDeleted = false,
                            Name = "Muz Yerli Kg",
                            Price = 51.899999999999999
                        },
                        new
                        {
                            Id = 4L,
                            FileId = 4L,
                            IsDeleted = false,
                            Name = "Portakal Sıkma File Kg",
                            Price = 16.899999999999999
                        },
                        new
                        {
                            Id = 5L,
                            FileId = 5L,
                            IsDeleted = false,
                            Name = "Maydonoz Adet",
                            Price = 15.949999999999999
                        },
                        new
                        {
                            Id = 6L,
                            FileId = 6L,
                            IsDeleted = false,
                            Name = "Hıyar Badem Paket Kg",
                            Price = 44.950000000000003
                        },
                        new
                        {
                            Id = 7L,
                            FileId = 7L,
                            IsDeleted = false,
                            Name = "Mandalina Murcot",
                            Price = 39.950000000000003
                        },
                        new
                        {
                            Id = 8L,
                            FileId = 8L,
                            IsDeleted = false,
                            Name = "Domates Kokteyl Kg",
                            Price = 69.950000000000003
                        },
                        new
                        {
                            Id = 9L,
                            FileId = 9L,
                            IsDeleted = false,
                            Name = "Elma Starking Kg",
                            Price = 34.899999999999999
                        },
                        new
                        {
                            Id = 10L,
                            FileId = 10L,
                            IsDeleted = false,
                            Name = "Kabak Sakız Kg",
                            Price = 34.950000000000003
                        },
                        new
                        {
                            Id = 11L,
                            FileId = 11L,
                            IsDeleted = false,
                            Name = "Domates Salkım Kg",
                            Price = 49.950000000000003
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
